# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Checkout
- task: Checkout@1

# Instalar .NET 8
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restaurar dependencias
- script: dotnet restore
  displayName: 'Restore dependencies'

# Compilar
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build project'

# Publicar
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

# Deploy a Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'
    appName: 'My-App-ProyectDemoGitHub'
    package: '$(Build.ArtifactStagingDirectory)'

