# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1. Checkout del código
- uses: actions/checkout@v4

# 2. Instalar SDK .NET 8
- uses: actions/setup-dotnet@v4
  with:
    dotnet-version: '8.x'

# 3. Restaurar dependencias
- name: Restore dependencies
  run: dotnet restore

# 4. Compilar
- name: Build
  run: dotnet build --configuration $(buildConfiguration)

# 5. Publicar (prepara archivos para deploy)
- name: Publish
  run: dotnet publish --configuration $(buildConfiguration) --output ./publish

# 6. Login a Azure
- name: Azure Login
  uses: azure/login@v2
  with:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}         # App Registration Client ID
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}         # Tenant ID
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Subscription ID

# 7. Deploy a Azure Web App
- name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v3
  with:
    app-name: 'My-App-ProyectDemoGitHub'
    slot-name: 'Production'
    package: './publish'

